In [14]:
import pandas as pd
import numpy as np
from math import sqrt

In [2]:
def getMedian(values):
    values.sort()
    n = len(values)
    m = n//2
    return values[m] if n%2 else (values[m-1]+values[m])*0.5
def getStdDevSample(values):
    a = sum(values)/len(values)
    n = len(values)-1
    return math.sqrt(sum([(v-a)**2 for v in values])/n) if 0 < n else 0

def getStdDevPopulation(values):
    a = sum(values)/len(values)
    return math.sqrt(sum([(v-a)**2 for v in values])/len(values))

def getLcv(values):
    n = len(values)
    sample = np.array(values)
    sample = np.sort(sample.reshape(n))[::-1]
    b0 = np.mean(sample)
    b1 = np.array([(n - j - 1) * sample[j] / n / (n - 1)
           for j in range(n)]).sum()
    b2 = np.array([(n - j - 1) * (n - j - 2) * sample[j] / n / (n - 1) / (n - 2)
           for j in range(n - 1)]).sum()
    lmom1 = b0
    lmom2 = 2 * b1 - b0
    lmom3 = 6 * (b2 - b1) + b0
    lcv = lmom2 / lmom1
    return lcv

def getLskew(values):
    n = len(values)
    sample = np.array(values)
    sample = np.sort(sample.reshape(n))[::-1]
    b0 = np.mean(sample)
    b1 = np.array([(n - j - 1) * sample[j] / n / (n - 1)
           for j in range(n)]).sum()
    b2 = np.array([(n - j - 1) * (n - j - 2) * sample[j] / n / (n - 1) / (n - 2)
           for j in range(n - 1)]).sum()
    lmom1 = b0
    lmom2 = 2 * b1 - b0
    lmom3 = 6 * (b2 - b1) + b0
    lskew = lmom3 / lmom2
    return lskew

In [ ]:
print (r)

In [3]:
pc = {(1,1):[2,2,2,2],
      (2,2):[3,3,3],
      (3,3):[4,4,4,4,4],
      (4,4):[5,5,5]}
#pc = {('x':1,'y':1,[2,2,2,2]}

stats = ('lcv','lskew')

func = {'minimum': min,
        'maximum': max,
        'median': getMedian,
        'average': lambda values: sum(values)/len(values),
        'standard deviation (sample)': getStdDevSample,
        'standard deviation (population)': getStdDevPopulation,
        'range': lambda values: max(values)-min(values),
        'number of points': len,
        'lcv':getLcv,
        'lskew':getLskew}

In [7]:
coord = [(x,y,values) for (x,y), values in pc.items()]
print (coord)

[(1, 1, [2, 2, 2, 2]), (2, 2, [3, 3, 3]), (3, 3, [4, 4, 4, 4, 4]), (4, 4, [5, 5, 5])]


In [13]:
print (pc[(1,1)])

[2, 2, 2, 2]


In [26]:
for i in range(5,3):
    print (i)

1
2


In [15]:
def distance(coord1,coord2):
    d = sqrt(pow(coord1[0]-coord2[0],2) + pow(coord1[1]-coord2[1],2))
    return d


In [4]:
import random

In [8]:
t = [random.randint(1,30) for v in range(1,10)]
print (t)

[24, 1, 16, 22, 22, 9, 11, 9, 16]


In [13]:
cells ={}
for i in range(100,1100,5):
    for j in range(300,1300,5):
        cells.setdefault((i,j),[]).append([random.randint(1,30) for v in range(1,10)])

#print (cells)

In [72]:
if cells[(90,90)] is True:
    print ("näinpä")
#print (distance((1,3),(5,3)))

KeyError: (90, 90)

In [80]:
keys = list(cells.keys())[0]
#kk = list(cells.keys())
print (keys)
x = [[keys[0]-5*i,keys[0]+5*i] for i in range(0,int(30/5+1),1)]
x = np.unique(np.concatenate(np.array(x)))
y = [[keys[1]-5*i,keys[1]+5*i] for i in range(0,int(30/5+1),1)]
y = np.unique(np.concatenate(np.array(y)))
#print (x[0])
#ref = []
#for i in x:
 #   for j in y:
  #      ref.append((i,j))
#print (ref)
#ref = np.array([x,y])
#print (ref)
#print (ref+5)
#print (ref[0][0])

(100, 300)


In [81]:
o = 1
for coord1 in cells:
    x = x + (coord1[0] - keys[0])
    y = y + (coord1[1] - keys[1])
    #print (coord1,(x,y))
    ref = []
    for i in x:
        for j in y:
            ref.append((i,j))
    
    val = [] #[cells[k] for k in ref if distance(coord1,keys)<=20]
    for k in ref:
        try:
            v = cells[k]
            if distance(coord1,k)<=30:
                val.append(v)
        except:
            continue
    val = np.concatenate(np.concatenate(np.array(val)))
    #print (val)
    keys = coord1
    #o+=1
    #print (o)
    #if o>3:
    #    break
    #k = [keys for keys in kk if distance(coord1,keys)<=20]

In [39]:
for coord1 in pc:
    print (coord1)
    tt = []
    keys = [keys for keys in pc if distance(coord1,keys)<3]
    print (keys)
    val = [pc[v] for v in keys]
    val = np.concatenate(np.array(val))
    print (val)

(1, 1)
[(1, 1), (2, 2), (3, 3)]
[2 2 2 2 3 3 3 4 4 4 4 4]
(2, 2)
[(1, 1), (2, 2), (3, 3), (4, 4)]
[2 2 2 2 3 3 3 4 4 4 4 4 5 5 5]
(3, 3)
[(1, 1), (2, 2), (3, 3), (4, 4)]
[2 2 2 2 3 3 3 4 4 4 4 4 5 5 5]
(4, 4)
[(2, 2), (3, 3), (4, 4)]
[3 3 3 4 4 4 4 4 5 5 5]


C:\Users\mkesala\AppData\Local\Temp\ipykernel_4512\3600067101.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  val = np.concatenate(np.array(val))


In [37]:
for (x,y), values in pc.items():
    print (x,y)
    tt = []
    keys = [(i,j) for (i,j) in pc if distance((x,y),(i,j))<3]
    print (keys)
    val = [pc[v] for v in keys]
    val = np.concatenate(np.array(val))
    print (val)
    #for (x,y) in pc:
     #   if 
    """
    for i in range(3):
        try:
            x1 = pc[(x+i,y)]
            x2 = pc[(x-i),y]
            y1 = pc[x,y+i]
            x2 = pc[x,y-1]
            xy1 = pc[x+i,y+i]
            xy2 = pc[x+i,y-i]
            xy3 = pc[]
            
            #print (t,i)
            tt.append(t)
        except:
            continue
    """
    #print (np.concatenate(np.array(tt)))

1 1
[(1, 1), (2, 2), (3, 3)]
[2 2 2 2 3 3 3 4 4 4 4 4]
2 2
[(1, 1), (2, 2), (3, 3), (4, 4)]
[2 2 2 2 3 3 3 4 4 4 4 4 5 5 5]
3 3
[(1, 1), (2, 2), (3, 3), (4, 4)]
[2 2 2 2 3 3 3 4 4 4 4 4 5 5 5]
4 4
[(2, 2), (3, 3), (4, 4)]
[3 3 3 4 4 4 4 4 5 5 5]


C:\Users\mkesala\AppData\Local\Temp\ipykernel_4512\1588256695.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  val = np.concatenate(np.array(val))


In [14]:
coord = [(x,y,[(i,func[i](values)) for i in stats]) for (x,y), values in pc.items()]
print (coord)

[(1, 1, [('lcv', -1.1102230246251565e-16), ('lskew', -2.0)]), (2, 2, [('lcv', 0.0), ('lskew', nan)]), (3, 3, [('lcv', -1.1102230246251565e-16), ('lskew', -2.0)]), (4, 4, [('lcv', 0.0), ('lskew', nan)])]


C:\Users\mkesala\AppData\Local\Temp\ipykernel_2512\4086928550.py:42: RuntimeWarning: invalid value encountered in double_scalars
  lskew = lmom3 / lmom2


In [15]:
for x,y,z in coord:
    print ((x,y))
    for (i,j) in z:
        print (i)
        print (j)

(1, 1)
lcv
-1.1102230246251565e-16
lskew
-2.0
(2, 2)
lcv
0.0
lskew
nan
(3, 3)
lcv
-1.1102230246251565e-16
lskew
-2.0
(4, 4)
lcv
0.0
lskew
nan
